### ISSUE TITLE
Couldn't process repo. Error:

### ISSUE THREAD

**Issue by brunolm** [codersrank-org/multi_repo_extractor#22]
Error message:

```
Couldn't process repo. Error:
```

No error is printed.

Adding a log here instead shows me the error:

```go
	err := cmd.Run()
	fmt.Printf("Error %s\n", err.Error())
```

Real error

```
exec: ".../multi_repo_extractor/repo_info_extractor/run-docker-headless.sh": file does not exist
```

**Comment by peti2001** [comment]
This repo is deprecated and the generated artefact is not supported anymore. It is going to be merged with the `repo_info_extractor`.
