### ISSUE TITLE
Don't automatically open the browser after program completed

### ISSUE THREAD

**Issue by alimgiray** [codersrank-org/multi_repo_extractor#7]
After the generation is completed don’t open the browser immediately. Show the link that will be opened and wait for the user to press enter to avoid surprises.

**Comment by KrishKayc** [comment]
@alimgiray I can try this, can you please assign this to me?

**Comment by KrishKayc** [comment]
@alimgiray Have created PR for this https://github.com/codersrank-org/multi_repo_extractor/pull/10.

**Comment by alimgiray** [comment]
@KrishKayc I'll look at it as soon as I have time.
